public enum Topic: String, Equatable, Hashable, CaseIterable, Decodable, Sendable {
    case heartbeat = "Heartbeat"
    case carDataZ = "CarData.z"
    case positionZ = "Position.z"
    case carData = "CarData"
    case position = "Position"
    case extrapolatedClock = "ExtrapolatedClock"
    case topThree = "TopThree"
    case timingStats = "TimingStats"
    case timingAppData = "TimingAppData"
    case weatherData = "WeatherData"
    case trackStatus = "TrackStatus"
    case driverList = "DriverList"
    case raceControlMessages = "RaceControlMessages"
    case sessionInfo = "SessionInfo"
    case sessionData = "SessionData"
    case lapCount = "LapCount"
    case timingData = "TimingData"
    case championshipPrediction = "ChampionshipPrediction"
    case teamRadio = "TeamRadio"
    case tyreStintSeries = "TyreStintSeries"
    case pitStopSeries = "PitStopSeries"
    case pitLaneTimeCollection = "PitLaneTimeCollection"
}
